### ISSUE TITLE
Installing HydroQGIS

### ISSUE THREAD

**Issue by pinhead001** [hellkite500/HydroQGIS#1]
I am interested in testing the hydroqgis plugin. I cloned the repository and copied it to the following directory:

C:\Program Files\QGIS Lyon\apps\qgis\plugins\HydroData

Running Qgis 2.12.1-Lyon, I am not able to see the python plugins installer option under the plugins menu or within the Manage and Install Plugins dialog. 

Do you have any suggestions on the steps required to install and test the plugin?

**Comment by hellkite500** [comment]
Chris,

When QGIS started, did it come up with any errors?  Also, do you have scipy
installed? It is a dependency of the flood frequency module, and it can be
tricky to install correctly on Windows.

Nels

**Comment by pinhead001** [comment]
No errors on QGIS startup. scipy is installed and appears to be working. I had the plugin in the wrong directory, it needed to be in  C:\Program Files\QGIS Lyon\apps\qgis\python\plugins

So now the problem appears to be installing pandas for the QGIS python. I have tried several tactics to get pandas installed, but to no avail. Are you running on windows or nix? Any suggestions?

**Comment by hellkite500** [comment]
Run predominately on Linux. Was in the process of testing on Windows when I
ran across the scipy issue.  Are you running more than one version of
python by any chance? Pandas needs to be in the Python path of the Python
version used by QGIS. If you used the osgeo installer, it has a standalone
Python packaged with it, and you have to make sure the packages are
installed under that.

**Comment by gourikadam** [comment]
Trying to Install HydroQGIS on windows 32 bit version by placing the directory in python, plugin folder of QGIS 2.18 .
Steps followed were
1. Unzip the folder HydroQGIS-master.zip
2.Renaming it to HydroQGIS
3.Copying the folder in <QGIS_2.18\apps\qgis\python\plugins\> path
4. Copying all the files located in <QGIS_2.18\apps\qgis\python\plugins\HydroQGIS\HydroData>to one level up ie in <<QGIS_2.18\apps\qgis\python\plugins\HydroQGIS\> folder
5. Restarting QGIS again

Error is 
"no module named HydroData.services.Point 
Traceback (most recent call last):
  File "E:/Hydro/QGIS_2.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "E:/Hydro/QGIS_2.18/apps/qgis/./python/plugins\HydroQGIS\__init__.py", line 34, in classFactory
    from .hydro_data import HydroData
  File "E:/Hydro/QGIS_2.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "E:/Hydro/QGIS_2.18/apps/qgis/./python/plugins\HydroQGIS\hydro_data.py", line 32, in 
    from tools.Deliniation import DeliniationTool
  File "E:/Hydro/QGIS_2.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "E:/Hydro/QGIS_2.18/apps/qgis/./python/plugins\HydroQGIS\tools\Deliniation.py", line 32, in 
    from HydroData.services.Point import PointWorker
  File "E:/Hydro/QGIS_2.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named HydroData.services.Point "

**Comment by hellkite500** [comment]
@gourikadam I have not tested this plugin in a windows environment, and I'm not super familiar with the required directory structures for Qgis on windows.  The error is coming from, I think, an issue with directory names.  The plugin folder name should be HydroData.  I think if you simply extract HydroQGIS-master.zip to QGIS_2.18\apps\qgis\python\plugins (or simply rename your HydroQGIS directory to HydroData) then python will be able to find the correct modules.
